AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda.sample
      Runtime: nodejs6.10
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET

